spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eshop-order-service-db
    username: root
    password: 1234

jwt:
  secret: secretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecret
  access-token-validity-in-seconds: 86400
  refresh-token-validity-in-seconds: 144000